### ISSUE TITLE
std::forward type signature error using cpptoml::datetime and compiling with clang

### ISSUE THREAD

**Issue by jonnew** [skystrife/cpptoml#25] opened 2015-11-10 03:08 UTC
I'm having trouble compiling some code that uses cpptoml with clang (g++ 4.8.4 works fine)

- Clang version: Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
- cpptoml SHA: 86c77a6c22b4c475a93694806766a6ac6f841a72

The offending code is this:

```c++

auto dt = cpptoml::make_value<cpptoml::datetime>(generateDateTime()); 

cpptoml::datetime generateDateTime() {

    // Generate current date-time 
    std::time_t raw_time;
    struct tm * time_info;
    char buffer[100];
    std::time(&raw_time);
    time_info = std::localtime(&raw_time);

    cpptoml::datetime dt;
    dt.year = time_info->tm_year + 1900;
    dt.month = time_info->tm_mon + 1;
    dt.day = time_info->tm_mday;
    dt.hour = time_info->tm_hour;
    dt.minute = time_info->tm_min;
    dt.second = time_info->tm_sec;

    return dt;
}
```
and the compiler error I'm getting is the following:
```
/home/jon/Public/Oat/debug/cpptoml/src/cpptoml/include/cpptoml.h:339:51: error: no matching function for call to 'forward'
        make_shared_enabler(T&& val) : value_type(std::forward<T>(val))
                                                  ^~~~~~~~~~~~~~~
/home/jon/Public/Oat/debug/cpptoml/src/cpptoml/include/cpptoml.h:337:12: note: in instantiation of member function 'cpptoml::make_value(cpptoml::datetime &&)::make_shared_enabler::make_shared_enabler' requested here
    struct make_shared_enabler : public value_type
           ^
/home/jon/Public/Oat/src/calibrator/Saver.cpp:146:24: note: in instantiation of function template specialization 'cpptoml::make_value<cpptoml::datetime>' requested here
    auto dt = cpptoml::make_value<cpptoml::datetime>(generateDateTime()); 
                       ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/move.h:76:5: note: candidate function [with _Tp = double] not viable: no known conversion from 'cpptoml::datetime' to
      'typename std::remove_reference<double>::type &' (aka 'double &') for 1st argument
    forward(typename std::remove_reference<_Tp>::type& __t) noexcept
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/move.h:87:5: note: candidate function [with _Tp = double] not viable: no known conversion from 'cpptoml::datetime' to 'typename std::remove_reference<double>::type'
      (aka 'double') for 1st argument
    forward(typename std::remove_reference<_Tp>::type&& __t) noexcept
    ^
1 warning and 1 error generated
```
Any ideas?

**Comment by skystrife** [comment] 2015-11-10 05:35
Duplicate of #26.

**Closed by skystrife** 2015-11-10 05:35 UTC
